version: '3'

services:
  web:
    build:
      context: .
    image: ${NESTJS_STARTER_IMAGE:-nestjs-starter:local}
    entrypoint: scripts/web-docker-entrypoint-dev.sh
    command: yarn start:debug
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ${DUMMY_MOUNT:-.:/app}

  db:
    image: postgres:13.4-alpine
    environment:
      # Login without password
      POSTGRES_HOST_AUTH_METHOD: "trust"
      # Auto-create test DB
      POSTGRES_DB: test
    ports:
      - "5432:5432"
